update database pocs
imperva/dsfkit pull request #413
Opened 2024-05-22 22:20 UTC by jsonar-cpapke

2024-05-26 07:21 UTC, eytannnaim approved these changes
I believe our tests doesn't verify audit actually reach the dsf hub. In case you haven't verified that already, you should.

2024-05-27 16:03 UTC, jsonar-cpapke commented
> I believe our tests doesn't verify audit actually reach the dsf hub. In case you haven't verified that already, you should.

I don't know how to test this, I've never actually set up sonar with data sources.

2024-05-29 08:01 UTC, eytannnaim commented
You should apply the `examples/aws/poc/dsf_deployment` example.
You can disable DAM, DRA, HADR, for faster deployment and making sure that `simulation_db_types_for_agentless` is set with the relevant postgres. After the deployment is up and running, it can take up to an hour for the audit to show up in the dsf hub dashboard.

2024-06-24 23:01 UTC, jagdeep-sonar approved these changes
ok.

2024-08-18 07:14 UTC, gabibeyo commented
Any news with Eytan's request?

2024-08-18 07:28 UTC, gabibeyo requested changes
Any update about Eytan's request?
@darya-abdollahzadeh 
@jsonar-cpapke

2024-08-19 18:44 UTC, jsonar-cpapke commented
I still don't really know how to do it, as I haven't actually interacted with the hub and have no idea how to check for audit data.

2024-09-03 09:00 UTC, imperva-admin commented
I will approve it. From my point of view Sonar team validated the fix

2024-09-03 09:00 UTC, imperva-admin approved these changes

2024-10-18 19:55 UTC, closed without merging