add secret for CIDR in dsf_poc_cli-dev
imperva/dsfkit pull request #433
Opened 2024-07-31 19:11 UTC by jagdeep-sonar

2024-08-01 07:39 UTC, lindanasredin requested changes
You've added the secret to the dev_dsf_poc job. You also need to add it to master_dsf_poc job. To find all the locations that need to be changed, you need to search the project for the ymls you've changed in the previous PR - "dsf_poc_cli" and "sonar_poc_cli". When I did that I discovered another location - release.yml. Please add the secret there as well. So to summarize, you need to add the secret in nightly_manager.yml in master_dsf_poc job and in release.yml in test_apply job. Thanks.

2024-08-02 00:17 UTC, jagdeep-sonar commented
Change requested has been made. please review.

2024-08-02 16:25 UTC, jsonar-cpapke approved these changes

2024-08-04 08:54 UTC, lindanasredin approved these changes

2024-08-06 18:33 UTC, merged