Adding additional tags to workflows
imperva/dsfkit pull request #440
Opened 2024-10-15 08:25 UTC by roiklorin

added additional tags variables to workflows that deploy AWS resources

2024-10-15 10:38 UTC, eytannnaim approved these changes

2024-10-30 08:17 UTC, lindanasredin requested changes

2024-10-30 08:17 UTC, lindanasredin commented on .github/workflows/dsf_poc_cli.yml
> +      #additional_tags:
Remove comment

2024-10-30 08:17 UTC, lindanasredin commented on .github/workflows/dsf_poc_cli.yml
> +      #additional_tags:
Remove comment

2024-10-30 08:17 UTC, lindanasredin commented on .github/workflows/dsf_poc_cli.yml
> +        terraform -chdir=$EXAMPLE_DIR plan -var dam_license=license.mprv -var additional_tags='${{ env.TF_VAR_additional_tags }}'
No need to pass environment variables

2024-10-30 08:17 UTC, lindanasredin commented on .github/workflows/dsf_poc_cli.yml
> +      run: terraform -chdir=$EXAMPLE_DIR apply -var dam_license=license.mprv -var additional_tags='${{ env.TF_VAR_additional_tags }}' -auto-approve
Remove

2024-10-30 08:17 UTC, lindanasredin commented on .github/workflows/nightly_manager.yml
> +      branch: adding-additional-tags-to-workflows
Leftovers

2024-10-30 14:02 UTC, lindanasredin approved these changes

2024-10-30 14:04 UTC, merged